name: test Project Linting

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        run: make install
      - name: test linting --pre-commit
        run: make lint